# Generated by Django 4.2.27 on 2025-12-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Loi Finances 2024'", max_length=100)),
                ('year', models.IntegerField(default=2024)),
                ('is_active', models.BooleanField(default=False, help_text='Only one legislation should be active at a time.')),
            ],
        ),
        migrations.CreateModel(
            name='UsufructScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=4, help_text='e.g. 0.9 for 90%', max_digits=5)),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usufruct_scales', to='succession_engine.legislation')),
            ],
            options={
                'ordering': ['max_age'],
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('CHILD', 'Child/Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], default='CHILD', max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for infinity', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='e.g. 0.05 for 5%', max_digits=5)),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_brackets', to='succession_engine.legislation')),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('CHILD', 'Child/Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other'), ('SPOUSE', 'Spouse/Partner')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='succession_engine.legislation')),
            ],
        ),
    ]
