# Generated by Django 4.2.27 on 2025-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('succession_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_data', models.JSONField(help_text='The SimulationInput JSON payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
