# Generated by Django 4.2.27 on 2025-12-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('succession_engine', '0002_simulationscenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('donation_type', models.CharField(max_length=50)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_heir_id', models.UUIDField(blank=True, null=True)),
                ('beneficiary_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('donation_date', models.DateField()),
                ('description', models.TextField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_declared_to_tax', models.BooleanField(blank=True, default=False, null=True)),
                ('tax_declaration_date', models.DateField(blank=True, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('occupation_duration_months', models.IntegerField(blank=True, null=True)),
                ('monthly_rental_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_repaid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('insurance_contract_reference', models.TextField(blank=True, null=True)),
                ('premium_amount_after_70', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notary_act_reference', models.TextField(blank=True, null=True)),
                ('notary_signature_date', models.DateField(blank=True, null=True)),
                ('notary_name', models.TextField(blank=True, null=True)),
                ('notary_city', models.TextField(blank=True, null=True)),
                ('notary_details_unknown', models.BooleanField(blank=True, default=False, null=True)),
                ('notary_search_hint', models.TextField(blank=True, null=True)),
                ('current_value_unknown', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'donations',
            },
        ),
    ]
